# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    git log -n 2
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host $(System.PullRequest.PullRequestId)'